# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SamplerRasterValues
                                 A QGIS plugin
 Amostra valores de pixels a partir de rasters e preenche atributos de shapefiles no QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-10-27
        copyright            : (C) 2023 by Francisco Camello
        email                : camelloncase@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Francisco Camello'
__date__ = '2023-10-27'
__copyright__ = '(C) 2023 by Francisco Camello'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SamplerRasterValues class from file SamplerRasterValues.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sampler_raster_values import SamplerRasterValuesPlugin
    return SamplerRasterValuesPlugin()
