# -*- coding: utf-8 -*-

"""
/***************************************************************************
 SamplerRasterValues
                                 A QGIS plugin
 Amostra valores de pixels a partir de rasters e preenche atributos de
 shapefiles no QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-10-27
        copyright            : (C) 2023 by Francisco Camello
        email                : camelloncase@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Francisco Camello'
__date__ = '2023-10-27'
__copyright__ = '(C) 2023 by Francisco Camello'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os

from qgis.PyQt.Qt import QVariant
from qgis.utils import iface
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessingParameterEnum, QgsProcessing, QgsRasterLayer, QgsPointXY,
                       QgsProcessingOutputVectorLayer,
                       QgsProcessingParameterBoolean, QgsProcessingParameterVectorLayer, QgsProcessingParameterFile,
                       QgsProcessingParameterFolderDestination,
                       QgsProcessingParameterString,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterField,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink)

from .services.system_service import SystemService
from .services.layer_services import LayerService


class BatchRasterValuesAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT_FOLDER = 'INPUT_FOLDER'
    INPUT_LAYER = 'INPUT_LAYER'
    AQUA_MODIS_VARIABLE = 'AQUA_MODIS_VARIABLE'
    INPUT_FIELD = 'INPUT_FIELD'
    NEW_FIELD = 'NEW_FIELD'
    DATE_FIELD = 'DATE_FIELD'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFile(
                self.INPUT_FOLDER,
                self.tr('Images folder'),
                behavior=QgsProcessingParameterFile.Folder
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT_LAYER,
                self.tr('Input point layer'),
                [QgsProcessing.TypeVectorPoint],
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.DATE_FIELD,
                self.tr('Field with the observation date'),
                parentLayerParameterName=self.INPUT_LAYER,
                type=QgsProcessingParameterField.DateTime,
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.INPUT_FIELD,
                self.tr('Field to save the pixel value'),
                parentLayerParameterName=self.INPUT_LAYER,
                type=QgsProcessingParameterField.Any,
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterString(
                self.NEW_FIELD,
                self.tr('New field name'),
                defaultValue='SAMPLE',
                optional=True
            )
        )

        self.addParameter(
            QgsProcessingParameterEnum(
                self.AQUA_MODIS_VARIABLE,
                self.tr('AQUA MODIS variable'),
                options=[self.tr('chlor_a - Chlorophyll concentration'),
                         self.tr('sst - Sea Surface Temperature (11 μ daytime)')],
                defaultValue=0,
                optional=False
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addOutput(
            QgsProcessingOutputVectorLayer(
                self.OUTPUT,
                self.tr("Original layer without empty geometries")
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        layerService = LayerService()
        systemService = SystemService()

        inputFolder = self.parameterAsFile(parameters, self.INPUT_FOLDER, context)
        inputPointLayer = self.parameterAsVectorLayer(parameters, self.INPUT_LAYER, context)
        aquaModisVariable = self.parameterAsInt(parameters, self.AQUA_MODIS_VARIABLE, context)
        layerAttribute = self.parameterAsString(parameters, self.INPUT_FIELD, context)
        dateField = self.parameterAsString(parameters, self.DATE_FIELD, context)
        newField = self.parameterAsString(parameters, self.NEW_FIELD, context)

        newFeatures = []

        if newField != 'SAMPLE':
            layerService.addNewField(inputPointLayer, newField, QVariant.Double)

        for imageFile in os.listdir(inputFolder):

            if imageFile.lower().endswith('.nc') and os.path.isfile(os.path.join(inputFolder, imageFile)):

                for feature in inputPointLayer.getFeatures():

                    startDate, endDate = systemService.getDateRange(imageFile)
                    dateObject = layerService.getDateFromFeature(feature, dateField)

                    isWithinRange = systemService.isDateWithinRange(dateObject, startDate, endDate)

                    if isWithinRange:
                        rasterLayer = layerService.createNetcdfRaster(aquaModisVariable, imageFile,
                                                                      os.path.join(inputFolder, imageFile))
                        if rasterLayer.isValid():
                            updatedFeature = layerService.extractValueFromRaster(rasterLayer, feature,
                                                                                 layerAttribute, newField)
                            newFeatures.append(updatedFeature)

                layerService.updateFeature(iface, inputPointLayer, newFeatures, feedback)

        return {self.OUTPUT: inputPointLayer}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Batch Values Extractor'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return BatchRasterValuesAlgorithm()
