# -*- coding: utf-8 -*-

"""
/***************************************************************************
 SystemService
                                 A QGIS plugin
 Amostra valores de pixels a partir de rasters e preenche atributos de
 shapefiles no QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-10-27
        copyright            : (C) 2023 by Francisco Camello
        email                : camelloncase@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Francisco Camello'
__date__ = '2023-10-27'
__copyright__ = '(C) 2023 by Francisco Camello'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os

from datetime import datetime
from qgis.core.additions.edit import edit
from qgis.core import QgsField, QgsPointXY, QgsRasterLayer


class SystemService:

    def __init__(self):
        pass

    def getDateRange(self, fileName):
        parts = self.splitString(fileName, '.')
        dateRangeStr = parts[1]
        startDateStr, endDateStr = self.splitString(dateRangeStr, '_')

        startDate = self.formatDate(startDateStr)
        endDate = self.formatDate(endDateStr)
        return startDate, endDate

    @staticmethod
    def isDateWithinRange(date, startDate, endDate):
        # Check if a date is within a specified date range
        return startDate <= date <= endDate

    @staticmethod
    def formatDate(stringDate):
        return datetime.strptime(stringDate, "%Y%m%d").date()

    @staticmethod
    def splitString(string, character):
        return string.split(character)
