# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BatchRasterValuesAlgorithm
                                 A QGIS plugin
 Amostra valores de pixels a partir de rasters e preenche atributos no QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-10-27
        copyright            : (C) 2023 by Francisco Camello
        email                : camelloncase@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Francisco Camello'
__date__ = '2023-10-27'
__copyright__ = '(C) 2023 by CamellOnCase'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os

from qgis.PyQt.Qt import QVariant
from qgis.utils import iface
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing, QgsProcessingParameterEnum, QgsProcessingParameterString,
                       QgsProcessingOutputVectorLayer, QgsProcessingException,
                       QgsProcessingParameterVectorLayer, QgsProcessingParameterFile,
                       QgsProcessingAlgorithm, QgsProcessingParameterField)

from ..services.system_service import SystemService
from ..services.layer_services import LayerService
from .help.algorithms_help import HTMLHelpCreator as Helper


class BatchSamplerRasterValuesAlgorithm(QgsProcessingAlgorithm):

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT_FOLDER = 'INPUT_FOLDER'
    INPUT_LAYER = 'INPUT_LAYER'
    AQUA_MODIS_VARIABLE = 'AQUA_MODIS_VARIABLE'
    INPUT_FIELD = 'INPUT_FIELD'
    NEW_FIELD = 'NEW_FIELD'
    DATE_FIELD = 'DATE_FIELD'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFile(
                self.INPUT_FOLDER,
                self.tr('Images folder'),
                behavior=QgsProcessingParameterFile.Folder
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT_LAYER,
                self.tr('Input point layer'),
                [QgsProcessing.TypeVectorPoint],
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.DATE_FIELD,
                self.tr('Field with the observation date'),
                parentLayerParameterName=self.INPUT_LAYER,
                type=QgsProcessingParameterField.DateTime,
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.INPUT_FIELD,
                self.tr('Field to save the pixel value'),
                parentLayerParameterName=self.INPUT_LAYER,
                type=QgsProcessingParameterField.Any,
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterString(
                self.NEW_FIELD,
                self.tr('Create a field for variable of interest'),
                defaultValue='SAMPLE',
                optional=True
            )
        )

        self.addParameter(
            QgsProcessingParameterEnum(
                self.AQUA_MODIS_VARIABLE,
                self.tr('AQUA MODIS variable'),
                options=[self.tr('chlor_a - Chlorophyll concentration'),
                         self.tr('sst - Sea Surface Temperature (11 μ daytime)')],
                defaultValue=0,
                optional=False
            )
        )

        self.addOutput(
            QgsProcessingOutputVectorLayer(
                self.OUTPUT,
                self.tr("Original layer without empty geometries")
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        layerService = LayerService()
        systemService = SystemService()

        inputFolder = self.parameterAsFile(parameters, self.INPUT_FOLDER, context)
        inputPointLayer = self.parameterAsVectorLayer(parameters, self.INPUT_LAYER, context)
        aquaModisVariable = self.parameterAsInt(parameters, self.AQUA_MODIS_VARIABLE, context)
        layerAttribute = self.parameterAsString(parameters, self.INPUT_FIELD, context)
        dateField = self.parameterAsString(parameters, self.DATE_FIELD, context)
        newField = self.parameterAsString(parameters, self.NEW_FIELD, context)

        if inputPointLayer.isEditable():
            raise QgsProcessingException(self.tr(f'Layer {inputPointLayer.name()} is in editable mode.'))

        newFeatures = []

        if newField != 'SAMPLE':
            layerService.addNewField(inputPointLayer, newField, QVariant.Double)

        netcdfImages = systemService.filterFilesInDirectory(inputFolder, '.nc')

        for imageFile in netcdfImages:

            if feedback.isCanceled():
                raise QgsProcessingException(self.tr('\nProcessing cancelled by the user!\n'))

            for feature in inputPointLayer.getFeatures():

                if layerService.checkFeatureDateRange(feature, imageFile, dateField):

                    rasterLayer = layerService.createNetcdfRaster(aquaModisVariable, imageFile,
                                                                  os.path.join(inputFolder, imageFile))
                    if rasterLayer.isValid():

                        updatedFeature = layerService.extractValueFromRaster(rasterLayer, feature,
                                                                             layerAttribute, newField)
                        newFeatures.append(updatedFeature)

                        feedback.pushInfo(self.tr(f'File {os.path.basename(imageFile)}, processed!\n '))

                    else:
                        raise QgsProcessingException(self.tr('\nInvalid raster!\n'))

            layerService.updateFeature(iface, inputPointLayer, newFeatures, feedback)

        return {self.OUTPUT: inputPointLayer}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'batch_values_extractor'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('Batch Values Extractor')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Extraction'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def shortHelpString(self):
        return Helper.shortHelpString(self.name())

    def createInstance(self):
        return BatchSamplerRasterValuesAlgorithm()
