# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreatePointsFromFileAlgorithm
                                 A QGIS plugin
 Amostra valores de pixels a partir de rasters e preenche atributos no QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-10-27
        copyright            : (C) 2023 by Francisco Camello
        email                : camelloncase@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Francisco Camello'
__date__ = '2023-11-08'
__copyright__ = '(C) 2023 by CamellOnCase'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import csv
import math
import os
import numpy as np
from datetime import datetime

import pandas as pd
from osgeo import gdal
from pandas._libs.tslibs.timestamps import Timestamp

from qgis.PyQt.Qt import QVariant
from qgis.utils import iface
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import QgsVectorLayer, QgsField, QgsFeature, QgsGeometry, QgsPointXY, QgsProject
from qgis.core import (QgsProcessing, QgsProcessingParameterEnum, QgsProcessingParameterString, QgsFeatureSink,
                       QgsProcessingOutputVectorLayer, QgsProcessingException,
                       QgsProcessingParameterVectorLayer, QgsProcessingParameterFile,
                       QgsProcessingAlgorithm, QgsProcessingParameterNumber, QgsProcessingParameterFeatureSink)

from ..services.layer_services import LayerService
from ..services.system_service import SystemService


class BatchSummarizedExtractorAlgorithm(QgsProcessingAlgorithm):
    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    INPUT_FILE = 'INPUT_FILE'
    DATE_FIELD = 'DATE_FIELD'
    INPUT_FOLDER = 'INPUT_FOLDER'
    AQUA_MODIS_VARIABLE = 'AQUA_MODIS_VARIABLE'
    BAND_NUMBER = 'BAND_NUMBER'
    OUTPUT = 'OUTPUT'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFile(
                self.INPUT_FILE,
                self.tr('Points spreadsheet'),
                behavior=QgsProcessingParameterFile.File
            )
        )

        self.addParameter(
            QgsProcessingParameterString(
                self.DATE_FIELD,
                self.tr('Date field'),
                defaultValue='Write the name of date field here',
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterFile(
                self.INPUT_FOLDER,
                self.tr('Images folder'),
                behavior=QgsProcessingParameterFile.Folder
            )
        )

        self.addParameter(
            QgsProcessingParameterEnum(
                self.BAND_NUMBER,
                self.tr('AQUA MODIS variable'),
                options=['1', '2', '3'],
                defaultValue=0,
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterEnum(
                self.AQUA_MODIS_VARIABLE,
                self.tr('AQUA MODIS variable'),
                options=[self.tr('chlor_a - Chlorophyll concentration'),
                         self.tr('sst - Sea Surface Temperature (11 μ daytime)')],
                defaultValue=0,
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Summarized values')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        layerService = LayerService()
        systemService = SystemService()

        inputFolder = self.parameterAsFile(parameters, self.INPUT_FOLDER, context)
        inputFile = self.parameterAsFile(parameters, self.INPUT_FILE, context)
        aquaModisVariable = self.parameterAsInt(parameters, self.AQUA_MODIS_VARIABLE, context)
        bandNumber = self.parameterAsInt(parameters, self.BAND_NUMBER, context)
        dateField = self.parameterAsString(parameters, self.DATE_FIELD, context)

        project = QgsProject.instance()
        project_crs = project.crs()

        pointDataFrame = pd.read_excel(inputFile)
        dateList = pointDataFrame[dateField].to_list()
        formattedDateList = []
        for date_string in dateList:
            date_object = datetime.strptime(date_string, '%y/%m/%d')
            formatted_date = date_object.strftime('%Y%m%d')
            formattedDateList.append(systemService.formatDate(formatted_date))

        variable = layerService.retrieveNetcdfVariable(aquaModisVariable)

        fields = layerService.createFields({'id': QVariant.Int, 'Observation date': QVariant.String,
                                            'Start date': QVariant.String, 'End date': QVariant.String, 'Variable': QVariant.String,
                                            'Minimum': QVariant.Double, 'Maximum': QVariant.Double, 'Median': QVariant.Double,
                                            'Mean': QVariant.Double, 'Stddev': QVariant.Double})

        (sink, destination_id) = self.parameterAsSink(parameters, self.OUTPUT, context, fields, 100, project_crs)

        netcdfImages = systemService.filterFilesInDirectory(inputFolder, '.nc')
        total = 100.0 / len(netcdfImages) if len(netcdfImages) else 0

        for current, imageFile in enumerate(netcdfImages):

            if feedback.isCanceled():
                raise QgsProcessingException(self.tr('\nProcessing cancelled by the user!\n'))

            dateRange = systemService.getDateRange(imageFile)

            for date in formattedDateList:
                if systemService.isDateWithinRange(date, dateRange[0], dateRange[1]):

                    rasterLayer = layerService.createNetcdfRaster(aquaModisVariable, imageFile,
                                                                  os.path.join(inputFolder, imageFile), True)

                    if rasterLayer is not None:

                        stats = layerService.getSummaryStatistics(rasterLayer, (bandNumber + 1))
                        feedback.pushInfo(self.tr(f'\n File {os.path.basename(imageFile)}, processed!'))
                        observationDate = datetime.strptime(str(date), '%Y-%m-%d').strftime('%d/%m/%Y')
                        startDate = datetime.strptime(str(dateRange[0]), '%Y-%m-%d').strftime('%d/%m/%Y')
                        endDate = datetime.strptime(str(dateRange[1]), '%Y-%m-%d').strftime('%d/%m/%Y')

                        feature = layerService.createFeature(fields, [current, observationDate, startDate, endDate,
                                                                      variable, stats])
                        sink.addFeature(feature, QgsFeatureSink.FastInsert)

                        feedback.setProgress(int(current * total))

                    else:
                        raise QgsProcessingException(self.tr('\nInvalid raster!\n'))

        return {self.OUTPUT: None}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Batch Summarized Values Extractor'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Extraction'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return BatchSummarizedExtractorAlgorithm()
